# Generated by Django 2.1.2 on 2018-10-08 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Short name')),
                ('territory', models.CharField(blank=True, max_length=200, verbose_name='Territory')),
                ('region', models.CharField(blank=True, choices=[('SW', 'South West')], max_length=10, verbose_name='Region')),
                ('frequency', models.CharField(blank=True, max_length=200, verbose_name='Frequency')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active?')),
                ('default_time', models.TimeField(blank=True, null=True, verbose_name='Default start time')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('gm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_pack_gm', to=settings.AUTH_USER_MODEL, verbose_name='GM')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_pack_sec', to=settings.AUTH_USER_MODEL, verbose_name='Sec')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('datetime', models.DateTimeField(verbose_name='Start time')),
                ('hare', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hare')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number')),
                ('on_down', models.CharField(blank=True, max_length=200, null=True, verbose_name='On down')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hash_diary.Pack', verbose_name='Pack')),
            ],
        ),
    ]
